[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = $HOST
db_port = $PORT
db_user = $USER
db_password = $PASSWORD
db_name = neondb
db_sslmode = require
proxy_mode = True