from . import approval_category
from . import approval_workflow
from . import approval_stage
from . import approval_rule
from . import approval_request
from . import approval_request_line
from . import approval_line
from . import approval_history
from . import approval_dashboard
from . import sale_order
from . import purchase_order
from . import hr_expense
from . import hr_leave
from . import stock_picking
from . import slide_channel